apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web-front
  namespace: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: vimal13/myweb:v1
        name: web