apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: debug
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    app: prometheus-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090 
      nodePort: 30001
